name: beast
description: A chat app build with Flutter + Firebase.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Cupertino Icons
  cupertino_icons: ^0.1.3

  # Stacked
  stacked: ^1.6.0
  # third-party services
  stacked_services: ^0.4.1
  # navigation
  auto_route: ^0.5.0
  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  # Flutter Spinkit
  flutter_spinkit: ^4.1.2+1
  # Logger
  logger: ^0.9.1

  # cached network image
  cached_network_image: ^2.2.0+1
  # flutter video compress
  flutter_video_compress: ^0.3.7+8
  # video player
  video_player: ^0.10.11+1
  # image picker
  image_picker: ^0.6.7+2
  # image cropper
  image_cropper: ^1.2.3

  # shimmer
  shimmer: ^1.1.1
  # gradient appbar
  gradient_app_bar: ^0.1.3

  # cloud firestore
  cloud_firestore: ^0.13.6
  # firebase auth
  firebase_auth: ^0.16.1
  # firebase storage
  firebase_storage: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.0
  auto_route_generator: ^0.5.0
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/title.png
    - assets/images/icon_large.png
